name: Create
on:
  workflow_dispatch:
  pull_request:

jobs:
  create-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create text file
        run: ./scripts/test.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: mytextfile.txt
