name: financial-connections-example maestro
on:
  pull_request:
    paths:
      - 'financial-connections/**'
      - 'financial-connections-example/**'
      - 'stripe-core/**'
      - 'payments-model/**'
      - 'dependencies.gradle'
jobs:
  # Checkout PR branch and build the APK
  build-pr:
    name: Build PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: End-to-end tests
        run: ./maestro/maestro-1.8.1/bin/maestro test maestro/fc-flow-testmode.yaml
      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: maestro/maestro-1.8.1/bin/maestro test maestro/fc-flow-testmode.yaml

