name: financial-connections-example maestro
on:
  pull_request:
    paths:
      - 'financial-connections/**'
      - 'financial-connections-example/**'
      - 'stripe-core/**'
      - 'payments-model/**'
      - 'dependencies.gradle'
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Install Maestro CLI
        run: |
          brew tap mobile-dev-inc/tap
          brew install maestro
      - name: Run Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          profile: Nexus 6
          script: |
            ./gradlew :financial-connections-example:installDebug
            maestro --platform android test maestro/fc-flow-testmode.yaml
      - name: Archive maestro screenshots
        uses: actions/upload-artifact@v3
        with:
          name: maestro-screenshots
          path: |
            *.png

